Change from using fprintf to fputs.
Fixes the following error:

runtime/tal_sockets.c:61:3: error: format not a string literal and no format arguments [-Werror=format-security]
fprintf(stderr, msg);